Scaled bipedal walker reward
smorad/popgym pull request #3
Opened 2022-07-03 09:02 UTC by matteobettini

2022-07-03 16:31 UTC, smorad commented on popgym/envs/bipedal_walker.py
> +            MAX_DELTA_POS * 130 / SCALE,
Where does the 130 come from?

2022-07-03 16:31 UTC, smorad commented on popgym/envs/bipedal_walker.py
> +MAX_DELTA_POS = (
You should set this in init so it is a function of `max_episode_length`. Currently, if the length changes then the reward no longer sums to one.

2022-07-03 16:32 UTC, smorad requested changes
Looks great, just a few small comments.

2022-07-03 16:34 UTC, matteobettini commented on popgym/envs/bipedal_walker.py
> +MAX_DELTA_POS = (
The max delta pos obtainable by a worker is independent of the `max_episode_length`. I calculate it using the data that was in the original environment (all terrain covered in 1600 steps). Are you sure the reward doesn't sum to 1? i tested it with diefferen legths (100,200,300) and the heuristic

2022-07-03 16:35 UTC, matteobettini commented on popgym/envs/bipedal_walker.py
> +            MAX_DELTA_POS * 130 / SCALE,
It comes from the reward function. It is yet another constant that they did not define, i ll define it

2022-07-06 05:11 UTC, smorad commented
Awesome, thanks!

2022-07-06 05:11 UTC, merged

2022-07-06 05:11 UTC, smorad commented
Awesome, thanks!